In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Canada_Hosp1_COVID_InpatientData.xlsx to Canada_Hosp1_COVID_InpatientData (1).xlsx

In [ ]:
admission = pd.read_excel("/content/Canada_Hosp1_COVID_InpatientData.xlsx", sheet_name="Data-at-admission")

In [ ]:
admission.head()

,id,reason_for_admission,age,sex,ethnicity,ethnicity_other,height,weight,comorbidities,comorbidities_other,...,pao2,pao2_fio2,ph,high_senstivity_cardiac_troponin,esr,inr,ferritin,d_dimer,crp,hs_crp
0,1,Fever [R50.9],74,Male,"""[]""",NaN,NaN,NaN,"""[\""Hypertension\"",\""Diabetes\"",\""Other\""]""","GERD (gastroesophageal reflux disease), Dement...",...,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,223.0,NaN
1,2,Pneumonia [J18.9],61,Female,"""[]""",NaN,154.9,73.6,"""[\""Hypertension\"",\""Other\""]""","Closed fracture of fifth metatarsal bone, Dive...",...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2354,95.6,NaN
2,3,Pneumonia [J18.9],58,Female,"""[]""",NaN,NaN,NaN,"""[\""Hypertension\""]""",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Suspected COVID-19 virus infection [U07.2],94,Male,"""[]""",NaN,182.8,66.2,"""[\""Hypertension\"",\""Other\""]""","Parkinson's Disease, Back pain, Benign Prostat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"Febrile respiratory illness [J98.9, R50.9]",91,Male,"""[]""",NaN,NaN,NaN,"""[\""Chronic cardiac disease (not hypertension)...","TAVI, Atrial fibrillation, Gastric Reflux, Pac...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
admission.shape

(508, 55)

In [ ]:
admission.columns

Index(['id', 'reason_for_admission', 'age', 'sex', 'ethnicity',
       'ethnicity_other', 'height', 'weight', 'comorbidities',
       'comorbidities_other', 'received_covid_vaccine', 'covid_vaccine',
       'medications', 'smoking_history', 'year_they_quit',
       'previous_er_visit_within_14_days', 'admission_disposition',
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'heart_rate',
       'respiratory_rate', 'oxygen_saturation', 'temperature', 'motor',
       'verbal', 'eye', 'intubated', 'wbc', 'rbc', 'hemoglobin', 'hematocrit',
       'mcv', 'mch', 'mchc', 'rdw', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'serum_creatinine', 'sodium', 'potassium',
       'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2', 'ph',
       'high_senstivity_cardiac_troponin', 'esr', 'inr', 'ferritin', 'd_dimer',
       'crp', 'hs_crp'],
      dtype='object')

In [ ]:
admission = admission[[
    'id',
    'age',
    'sex',
    'height',
    'weight',
    'comorbidities',
    'systolic_blood_pressure',
    'diastolic_blood_pressure',
    'heart_rate',
    'respiratory_rate',
    'oxygen_saturation',
    'temperature',
    'motor',
    'verbal',
    'eye',
    'wbc',
    'rbc',
    'hemoglobin',
    'hematocrit',
    'mcv',
    'mch',
    'mchc',
    'rdw',
    'platelet_count',
    'aptt_aptr',
    'pt',
    'alt',
    'ast',
    'serum_creatinine',
    'sodium',
    'potassium',
    'total_serum_bilirubin',
    'lactate',
    'pao2',
    'pao2_fio2',
    'ph',
    'high_senstivity_cardiac_troponin',
    'esr',
    'inr',
    'ferritin',
    'd_dimer',
    'crp',
    'hs_crp',
    'intubated'
]]

In [ ]:
admission.shape

(508, 44)

In [ ]:
hlos = pd.read_excel("/content/Canada_Hosp1_COVID_InpatientData.xlsx", sheet_name="Hospital-length-of-stay")

In [ ]:
hlos.head()

,id,parent_id,did_the_patient_expire_in_hospital,reason_for_death,days_in_hospital_prior_to_expiration,hospital_length_of_stay,icu_length_of_stay,days_in_hospital_prior_to_icu_admission,time_on_mechanical_ventilation,days_in_hospital_prior_to_mechanical_ventilation,days_to_first_covid19_test_negative
0,1,1,Yes,Hospital acquired Pneumonia,20.0,21,NaN,NaN,NaN,NaN,NaN
1,2,2,No,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN
2,3,3,No,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
3,4,4,Yes,COVID-19 Pneumonia,9.0,9,NaN,NaN,NaN,NaN,NaN
4,5,5,Yes,COVID-Pneumonia,9.0,9,NaN,NaN,NaN,NaN,NaN

In [ ]:
hlos = hlos[['parent_id', 'hospital_length_of_stay']]

In [ ]:
hlos.head()

   parent_id  hospital_length_of_stay
0          1                       21
1          2                        5
2          3                        7
3          4                        9
4          5                        9

In [ ]:
admission = admission.merge(
    hlos,
    left_on='id',
    right_on='parent_id'
)

In [ ]:
admission = admission.drop(columns=['parent_id'])

In [ ]:
admission.shape

(508, 45)

In [ ]:
admission.isnull().sum()

id                                    0
age                                   0
sex                                   0
height                              236
weight                              150
comorbidities                         0
systolic_blood_pressure               0
diastolic_blood_pressure              0
heart_rate                            0
respiratory_rate                      0
oxygen_saturation                     0
temperature                           0
motor                                 2
verbal                                2
eye                                   2
wbc                                   2
rbc                                   2
hemoglobin                            2
hematocrit                            2
mcv                                   2
mch                                   2
mchc                                  2
rdw                                   2
platelet_count                        2
aptt_aptr                           220
pt                                  193
alt                                 105
ast                                 105
serum_creatinine                      2
sodium                                2
potassium                             2
total_serum_bilirubin               105
lactate                             146
pao2                                476
pao2_fio2                           485
ph                                  476
high_senstivity_cardiac_troponin    508
esr                                 503
inr                                 193
ferritin                            488
d_dimer                             256
crp                                 366
hs_crp                              508
intubated                             0
hospital_length_of_stay               0
dtype: int64

In [ ]:
admission = admission.drop(columns=[
    'high_senstivity_cardiac_troponin',
    'hs_crp'
])

In [ ]:
admission.shape

(508, 43)

In [ ]:
admission['aptt_aptr'] = admission['aptt_aptr'].replace('>150', '150')

admission['aptt_aptr'] = pd.to_numeric(admission['aptt_aptr'])

In [ ]:
admission = admission.fillna(admission.mean(numeric_only=True))

In [ ]:
admission.isnull().sum()

id                            0
age                           0
sex                           0
height                        0
weight                        0
comorbidities                 0
systolic_blood_pressure       0
diastolic_blood_pressure      0
heart_rate                    0
respiratory_rate              0
oxygen_saturation             0
temperature                   0
motor                         0
verbal                        0
eye                           0
wbc                           0
rbc                           0
hemoglobin                    0
hematocrit                    0
mcv                           0
mch                           0
mchc                          0
rdw                           0
platelet_count                0
aptt_aptr                     0
pt                            0
alt                           0
ast                           0
serum_creatinine              0
sodium                        0
potassium                     0
total_serum_bilirubin         0
lactate                       0
pao2                          0
pao2_fio2                     0
ph                            0
esr                           0
inr                           0
ferritin                      0
d_dimer                     256
crp                           0
intubated                     0
hospital_length_of_stay       0
dtype: int64

In [ ]:
admission['d_dimer'] = pd.to_numeric(admission['d_dimer'], errors='coerce')

In [ ]:
admission['d_dimer'] = admission['d_dimer'].fillna(admission['d_dimer'].mean())

In [ ]:
admission.isnull().sum().sum()

np.int64(0)

In [ ]:
print("Number of patients:", admission.shape[0])
print("Number of columns:", admission.shape[1])

Number of patients: 508
Number of columns: 43

In [ ]:
admission.mean(numeric_only=True)

id                           260.877953
age                           66.027559
height                       166.911029
weight                        80.265922
systolic_blood_pressure      129.362205
diastolic_blood_pressure      75.566929
heart_rate                    97.397638
respiratory_rate              24.901575
oxygen_saturation             93.100394
temperature                   37.768110
motor                          5.913043
verbal                         4.768775
eye                            3.944664
wbc                            8.032609
rbc                            4.624723
hemoglobin                   129.875494
hematocrit                     0.395055
mcv                           86.026877
mch                           28.289130
mchc                         328.581028
rdw                           13.973123
platelet_count               230.934783
aptt_aptr                     31.326389
pt                            14.618095
alt                           51.248139
ast                           61.399504
serum_creatinine             114.778656
sodium                       135.330040
potassium                      3.885771
total_serum_bilirubin         10.630273
lactate                        2.330663
pao2                          77.906250
pao2_fio2                      1.500000
ph                             7.347500
esr                           61.800000
inr                            1.159365
ferritin                    1003.750000
d_dimer                     1289.987705
crp                          109.128873
hospital_length_of_stay       12.433071
dtype: float64

In [ ]:
zero_columns = (admission == 0).all()

print("Number of all-zero columns:", zero_columns.sum())

Number of all-zero columns: 0

In [ ]:
admission = admission.drop(columns=['id'])

In [ ]:
admission = pd.get_dummies(admission)

In [ ]:
admission.head()

,age,height,weight,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,motor,...,"comorbidities_""[\""Obesity\""]""","comorbidities_""[\""Other\""]""","comorbidities_""[\""Pregnancy\"",\""Other\""]""","comorbidities_""[\""Pregnancy\""]""","comorbidities_""[\""Rheumatologic disorder\"",\""Hematological\"",\""Other\""]""","comorbidities_""[\""Rheumatologic disorder\"",\""Other\""]""","comorbidities_""[\""Stroke\"",\""Other\""]""","comorbidities_""[]""",intubated_No,intubated_Yes
0,74,166.911029,80.265922,99,62,85,20,93,37.5,6.0,...,False,False,False,False,False,False,False,False,True,False
1,61,154.900000,73.600000,122,77,93,36,88,38.0,6.0,...,False,False,False,False,False,False,False,False,True,False
2,58,166.911029,80.265922,109,72,73,24,91,38.3,6.0,...,False,False,False,False,False,False,False,False,True,False
3,94,182.800000,66.200000,165,71,92,16,96,37.5,6.0,...,False,False,False,False,False,False,False,False,True,False
4,91,166.911029,80.265922,131,76,60,18,95,38.2,6.0,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
X = admission.drop(columns=['hospital_length_of_stay'])

y = admission['hospital_length_of_stay']

In [ ]:
print(X.shape)
print(y.shape)

(508, 179)
(508,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [ ]:
print("Training patients:", len(X_train))
print("Testing patients:", len(X_test))

Training patients: 406
Testing patients: 102

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(406, 179)
(102, 179)

In [ ]:
model1 = Sequential()

model1.add(Dense(32, activation='relu'))
model1.add(Dense(1))

model1.compile(optimizer='adam', loss='mse')

model1.fit(X_train, y_train, epochs=20)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 323.0688
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 307.1446
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 292.2565
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 279.4327
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 267.0823
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 255.6674
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 243.8482
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 233.3442
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 222.8261
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 212.7256
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 202.5225
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 193.1560
Epoch 13/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 183.4565
Epoch 14/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 174.5869
Epoch 15/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 165.9420
Epoch 16/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 157.9899
Epoch 17/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 150.2024
Epoch 18/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 142.8066
Epoch 19/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 136.6685
Epoch 20/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 130.4462

In [ ]:
train_mse1 = model1.evaluate(X_train, y_train)

test_mse1 = model1.evaluate(X_test, y_test)

print("Training MSE:", train_mse1)
print("Testing MSE:", test_mse1)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 126.7565
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 157.6838
Training MSE: 126.75650024414062
Testing MSE: 157.68380737304688

In [ ]:
model2 = Sequential()

model2.add(Dense(64, activation='relu'))
model2.add(Dense(1))

model2.compile(optimizer='adam', loss='mse')

model2.fit(X_train, y_train, epochs=20)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 297.8561
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 277.9604
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 260.4722
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 243.5954
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 227.0679
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.4217
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 196.3092
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 180.6934
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.1422
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 153.0428
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 141.8023
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 130.5068
Epoch 13/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 120.8804
Epoch 14/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 112.9897
Epoch 15/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.3742
Epoch 16/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.6936
Epoch 17/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 96.6821
Epoch 18/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92.4752
Epoch 19/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 89.5299
Epoch 20/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 86.8357

In [ ]:
train_mse2 = model2.evaluate(X_train, y_train)

test_mse2 = model2.evaluate(X_test, y_test)

print("Training MSE:", train_mse2)
print("Testing MSE:", test_mse2)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 85.0488
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 141.5820
Training MSE: 85.04875183105469
Testing MSE: 141.5819854736328

In [ ]:
model3 = Sequential()

model3.add(Dense(64, activation='relu'))
model3.add(Dense(1))

model3.compile(optimizer='adam', loss='mse')

model3.fit(X_train, y_train, epochs=50)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 320.8305
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 297.8299
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 278.7416
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 260.9127
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 244.3616
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 228.8788
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 214.5065
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 200.1488
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 186.5112
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 173.1638
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 161.2949
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 149.7393
Epoch 13/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 138.6708
Epoch 14/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 129.4369
Epoch 15/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 120.7261
Epoch 16/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 113.5485
Epoch 17/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 107.3629
Epoch 18/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 101.6570
Epoch 19/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97.6069
Epoch 20/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 93.6298
Epoch 21/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 90.6825
Epoch 22/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 88.3418
Epoch 23/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.8158
Epoch 24/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83.6537
Epoch 25/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 81.9760
Epoch 26/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.9796
Epoch 27/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 78.2478
Epoch 28/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.8550
Epoch 29/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.2273
Epoch 30/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.8995
Epoch 31/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.5161
Epoch 32/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.1633
Epoch 33/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.8904
Epoch 34/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.8046
Epoch 35/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 67.6743
Epoch 36/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 66.6877
Epoch 37/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 65.5208
Epoch 38/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 64.4097
Epoch 39/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 63.5879
Epoch 40/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 62.4598
Epoch 41/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 61.5996
Epoch 42/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 60.6017
Epoch 43/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 59.8341
Epoch 44/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 58.9347
Epoch 45/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 58.0222
Epoch 46/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 57.3458
Epoch 47/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.4001
Epoch 48/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55.6320
Epoch 49/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 54.8170
Epoch 50/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54.0060

In [ ]:
train_mse3 = model3.evaluate(X_train, y_train)

test_mse3 = model3.evaluate(X_test, y_test)

print("Training MSE:", train_mse3)
print("Testing MSE:", test_mse3)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 53.3253
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 169.9843
Training MSE: 53.32530212402344
Testing MSE: 169.9843292236328

In [ ]:
days = pd.read_excel(
    "/content/Canada_Hosp1_COVID_InpatientData.xlsx",
    sheet_name="Days-breakdown"
)

In [ ]:
days.shape

(4064, 70)

In [ ]:
days = days.merge(hlos, on='parent_id')

In [ ]:
days['remaining_hlos'] = days['hospital_length_of_stay'] - days['day']

In [ ]:
days[['parent_id', 'day', 'hospital_length_of_stay', 'remaining_hlos']].head()

   parent_id  day  hospital_length_of_stay  remaining_hlos
0          1    1                       21              20
1          1    2                       21              19
2          1    3                       21              18
3          1    4                       21              17
4          1    5                       21              16

In [ ]:
days = days[days['remaining_hlos'] >= 0]

In [ ]:
days.shape

(3121, 72)

In [ ]:
days.columns

Index(['id', 'parent_id', 'day', 'systolic_blood_pressure',
       'diastolic_blood_pressure', 'heart_rate', 'respiratory_rate',
       'oxygen_saturation', 'temperature', 'highest_mean_arterial_pressure',
       'lowest_mean_arterial_pressure', 'highest_heart_rate',
       'lowest_heart_rate', 'highest_creatinine', 'lowest_urine_output',
       'highest_gcs', 'lowest_gcs', 'intubated', 'highest_ph', 'lowest_ph',
       'cardiac_arrest', 'arrested_time', 'major_cardiac_events',
       'clinically_diagnosed_infections', 'mechanical_ventilation',
       'number_of_vasoactive_agents', 'antiarrhythmic_therapies',
       'renal_replacement_therapy_dialysis',
       'cardiovascular_mechanical_support', 'fluid_balance', 'wbc', 'rbc',
       'hemoglobin', 'hematocrit', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'mch', 'mcv', 'mchc', 'rdw', 'serum_creatinine', 'sodium',
       'potassium', 'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2',
       'ph', 'high_sensitivity_cardiac_troponin', 'esr', 'inr', 'ferritin',
       'd_dimer', 'crp', 'hs_crp', 'echocardiogram', 'ejection_fraction',
       'wall_motion_abnormality', 'chest_x_ray', 'cxr_findings', 'chest_ct',
       'chest_ct_findings', 'head_ct', 'head_ct_findings', 'antimicrobial',
       'anticoagulation', 'steroid', 'hospital_length_of_stay',
       'remaining_hlos'],
      dtype='object')

In [ ]:
days = days[[
    'parent_id',
    'day',
    'systolic_blood_pressure',
    'diastolic_blood_pressure',
    'heart_rate',
    'respiratory_rate',
    'oxygen_saturation',
    'temperature',
    'intubated',
    'wbc',
    'rbc',
    'hemoglobin',
    'hematocrit',
    'platelet_count',
    'aptt_aptr',
    'pt',
    'alt',
    'ast',
    'mch',
    'mcv',
    'mchc',
    'rdw',
    'serum_creatinine',
    'sodium',
    'potassium',
    'total_serum_bilirubin',
    'lactate',
    'pao2',
    'pao2_fio2',
    'ph',
    'esr',
    'inr',
    'ferritin',
    'd_dimer',
    'crp',
    'hs_crp',
    'remaining_hlos'
]]

In [ ]:
days.shape

(3121, 37)

In [ ]:
days.isnull().sum()

parent_id                      0
day                            0
systolic_blood_pressure       33
diastolic_blood_pressure      33
heart_rate                    16
respiratory_rate              18
oxygen_saturation             16
temperature                   20
intubated                      0
wbc                         1379
rbc                         1379
hemoglobin                  1379
hematocrit                  1379
platelet_count              1384
aptt_aptr                   2941
pt                          2869
alt                         2674
ast                         2674
mch                         1379
mcv                         1379
mchc                        1379
rdw                         1379
serum_creatinine            1108
sodium                      1472
potassium                   1421
total_serum_bilirubin       2672
lactate                     2933
pao2                        2800
pao2_fio2                   2854
ph                          2805
esr                         3112
inr                         2869
ferritin                    3015
d_dimer                     2822
crp                         2844
hs_crp                      3121
remaining_hlos                 0
dtype: int64

In [ ]:
days = days.drop(columns=['hs_crp'])

In [ ]:
for column in days.columns:
    if column != 'intubated':
        days[column] = pd.to_numeric(days[column], errors='coerce')

In [ ]:
days = days.fillna(days.mean(numeric_only=True))

In [ ]:
days.isnull().sum().sum()

np.int64(0)

In [ ]:
days = pd.get_dummies(days)

In [ ]:
days.shape

(3121, 37)

In [ ]:
patients = days['parent_id'].unique()

train_patients, test_patients = train_test_split(
    patients,
    test_size=0.20,
    random_state=42
)

In [ ]:
print("Training patients:", len(train_patients))
print("Testing patients:", len(test_patients))

Training patients: 406
Testing patients: 102

In [ ]:
train_days = days[days['parent_id'].isin(train_patients)]

test_days = days[days['parent_id'].isin(test_patients)]

In [ ]:
print(train_days.shape)
print(test_days.shape)

(2485, 37)
(636, 37)

In [ ]:
X_columns = days.columns.drop([
    'parent_id',
    'day',
    'remaining_hlos'
])

In [ ]:
len(X_columns)

34

In [ ]:
train_days = train_days.copy()
test_days = test_days.copy()

train_days.loc[:, X_columns] = rnn_scaler.fit_transform(
    train_days[X_columns]
)

test_days.loc[:, X_columns] = rnn_scaler.transform(
    test_days[X_columns]
)

In [ ]:
print(train_days.shape)
print(test_days.shape)

(2485, 37)
(636, 37)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
X_train_rnn = []
y_train_rnn = []

for patient in train_patients:
    patient_data = train_days[train_days['parent_id'] == patient]
    patient_data = patient_data.sort_values('day')

    X_train_rnn.append(patient_data[X_columns].values)
    y_train_rnn.append(patient_data['remaining_hlos'].iloc[-1])

In [ ]:
X_test_rnn = []
y_test_rnn = []

for patient in test_patients:
    patient_data = test_days[test_days['parent_id'] == patient]
    patient_data = patient_data.sort_values('day')

    X_test_rnn.append(patient_data[X_columns].values)
    y_test_rnn.append(patient_data['remaining_hlos'].iloc[-1])

In [ ]:
X_train_rnn = pad_sequences(
    X_train_rnn,
    padding='post',
    dtype='float32'
)

X_test_rnn = pad_sequences(
    X_test_rnn,
    padding='post',
    dtype='float32',
    maxlen=X_train_rnn.shape[1]
)

In [ ]:
y_train_rnn = np.array(y_train_rnn)
y_test_rnn = np.array(y_test_rnn)

In [ ]:
print("X train:", X_train_rnn.shape)
print("X test:", X_test_rnn.shape)

print("y train:", y_train_rnn.shape)
print("y test:", y_test_rnn.shape)

X train: (406, 8, 34)
X test: (102, 8, 34)
y train: (406,)
y test: (102,)

In [ ]:
from tensorflow.keras.layers import SimpleRNN, Masking

In [ ]:
rnn1 = Sequential()

rnn1.add(Masking(mask_value=0.0))
rnn1.add(SimpleRNN(32, activation='relu'))
rnn1.add(Dense(1))

rnn1.compile(optimizer='adam', loss='mse')

In [ ]:
rnn1.fit(
    X_train_rnn,
    y_train_rnn,
    epochs=20
)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 113.9677
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 103.0327
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 95.6132
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 88.1356
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.6637
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 73.2665
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7815
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1773
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.3205
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.2453
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3079
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.6046
Epoch 13/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49.7217
Epoch 14/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.4187
Epoch 15/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.2391
Epoch 16/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 42.8954
Epoch 17/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.5679
Epoch 18/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38.4651
Epoch 19/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 36.4520
Epoch 20/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34.6261

In [ ]:
train_mse_rnn1 = rnn1.evaluate(X_train_rnn, y_train_rnn)
test_mse_rnn1 = rnn1.evaluate(X_test_rnn, y_test_rnn)

print("RNN Training MSE:", train_mse_rnn1)
print("RNN Testing MSE:", test_mse_rnn1)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 32.2329
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 70.4415
RNN Training MSE: 32.23294448852539
RNN Testing MSE: 70.4415283203125

In [ ]:
rnn2 = Sequential()

rnn2.add(Masking(mask_value=0.0))
rnn2.add(SimpleRNN(64, activation='relu'))
rnn2.add(Dense(1))

rnn2.compile(optimizer='adam', loss='mse')

rnn2.fit(
    X_train_rnn,
    y_train_rnn,
    epochs=20
)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 9s 24ms/step - loss: 97.1452
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 77.3996
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 73.7465
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 67.7987
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 63.5589
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2850
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54.5120
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50.5031
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.0853
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 43.3472
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.7756
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.3562
Epoch 13/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.3765
Epoch 14/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.7447
Epoch 15/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.0964
Epoch 16/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.7309
Epoch 17/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20.9708
Epoch 18/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.5851
Epoch 19/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.1995
Epoch 20/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.5107

In [ ]:
train_mse_rnn2 = rnn2.evaluate(X_train_rnn, y_train_rnn)
test_mse_rnn2 = rnn2.evaluate(X_test_rnn, y_test_rnn)

print("RNN Model 2 Training MSE:", train_mse_rnn2)
print("RNN Model 2 Testing MSE:", test_mse_rnn2)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 12.2407
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 82.8660
RNN Model 2 Training MSE: 12.240671157836914
RNN Model 2 Testing MSE: 82.86601257324219

In [ ]:
rnn3 = Sequential()

rnn3.add(Masking(mask_value=0.0))
rnn3.add(SimpleRNN(64, activation='relu'))
rnn3.add(Dense(1))

rnn3.compile(optimizer='adam', loss='mse')

rnn3.fit(
    X_train_rnn,
    y_train_rnn,
    epochs=50
)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 93.0497
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 79.2074
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68.4358
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 63.4413
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 57.8982
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 53.6144
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 49.7304
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 46.7365
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 42.9737
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 39.4735
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 36.1227
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32.8667
Epoch 13/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.7591
Epoch 14/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.5837
Epoch 15/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 22.7837
Epoch 16/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 19.5109
Epoch 17/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 16.2635
Epoch 18/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 14.3587
Epoch 19/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 11.9787
Epoch 20/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 9.9314
Epoch 21/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 8.2051
Epoch 22/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 8.0388
Epoch 23/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.9132
Epoch 24/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.2369
Epoch 25/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.6351
Epoch 26/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.1284
Epoch 27/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5363
Epoch 28/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2193
Epoch 29/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.8715
Epoch 30/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5113
Epoch 31/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5628
Epoch 32/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7195
Epoch 33/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5547
Epoch 34/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1816
Epoch 35/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0291
Epoch 36/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3775
Epoch 37/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2239
Epoch 38/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6995
Epoch 39/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4440
Epoch 40/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.4478
Epoch 41/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1193
Epoch 42/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6426
Epoch 43/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4335
Epoch 44/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0118
Epoch 45/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0960
Epoch 46/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1564
Epoch 47/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1062
Epoch 48/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9728
Epoch 49/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7712
Epoch 50/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6713

In [ ]:
train_mse_rnn3 = rnn3.evaluate(X_train_rnn, y_train_rnn)
test_mse_rnn3 = rnn3.evaluate(X_test_rnn, y_test_rnn)

print("RNN Model 3 Training MSE:", train_mse_rnn3)
print("RNN Model 3 Testing MSE:", test_mse_rnn3)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5177
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 86.1876
RNN Model 3 Training MSE: 0.5176554918289185
RNN Model 3 Testing MSE: 86.18756103515625